[package]
name = "labjack"
version = "0.1.0"
edition = "2021"

[dependencies]
modbus = "1.1.0"
phf = { version = "0.11.2", features = ["macros"] }

[build-dependencies]
phf = { version = "0.11.2", default-features = false }
phf_codegen = "0.11.2"