name: Format & Clippy

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Rust Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install `rustfmt`
        run: rustup component add rustfmt

      - name: Install `clippy`
        run: rustup component add clippy

      - name: 🔍 Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: 🔍 Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
